--moyenne du nombre d’usagers par vélo par jour
SELECT avg(NBR_USAGER)/30 as MOYENNE_NBR_USAGERS
from
(
SELECT count(*) as NBR_USAGER, DATEDIFF(DATE(NOW()),DATE(DATE_DEPART)) as DIFFDATE
from EMPRUNT inner join VELO 
on EMPRUNT.NUMERO_REFERENCE=VELO.NUMERO_REFERENCE
where DIFFDATE<=30
group by VELO.NUMERO_REFERENCE
);

--moyenne des distances parcourues par les vélos sur une semaine
SELECT avg(DISTANCE_TOTALE)
from
(
SELECT sum(DISTANCE) as DISTANCE_TOTALE, DATEDIFF(DATE(NOW()),DATE(DATE_DEPART)) as DIFFDATE
from (VELO inner join EMPRUNT on VELO.NUMERO_REFERENCE=EMPRUNT.NUMERO_REFERENCE)
inner join ETRE_DISTANT
on EMPRUNT.NUMERO_STATION_DEPART=ETRE_DISTANT.NUMERO_STATION_DEPART 
and EMPRUNT.NUMERO_STATION_ARRIVEE=ETRE_DISTANT.NUMERO_STATION_ARRIVEE 
where DIFFDATE<=7
group by VELO.NUMERO_REFERENCE
);

--classement des stations par nombre de places disponibles par commune
SELECT *
from STATION
order by COMMUNE,NOMBRE_BORNES;

--classement des vélos les plus chargés par station
SELECT STATION.NUMERO_STATION, STATION.ADRESSE_STATION, VELO.*
from STATION inner join VELO 
on STATION.NUMERO_STATION=VELO.NUMERO_STATION
order by STATION.NUMERO_STATION,NIVEAU_CHARGE desc;